'use client';

import React, { useState } from 'react';
import { Voucher, UserRole, PaymentStatus } from '@/types/database';
import { 
  FileText, 
  CheckCircle2, 
  Clock, 
  Send, 
  QrCode, 
  Eye, 
  Filter, 
  Search, 
  ArrowUpDown,
  Building,
  Calendar,
  IndianRupee,
  ShieldCheck,
  RefreshCw,
  Share2,
  ChevronRight,
  Sparkles
} from 'lucide-react';

interface VoucherListProps {
  vouchers: Voucher[];
  activeRole: UserRole;
  onSelectVoucher: (voucher: Voucher) => void;
  onUpdateStatus: (id: string, status: PaymentStatus) => void;
  onGenerateIrn: (id: string) => void;
  generatingIrnId: string | null;
}

export default function VoucherList({
  vouchers,
  activeRole,
  onSelectVoucher,
  onUpdateStatus,
  onGenerateIrn,
  generatingIrnId
}: VoucherListProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<string>('all');

  const filteredVouchers = vouchers.filter((v) => {
    const matchesSearch = 
      v.party_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      v.voucher_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (v.party_gstin && v.party_gstin.toLowerCase().includes(searchTerm.toLowerCase()));

    const matchesStatus = statusFilter === 'all' || v.status === statusFilter;
    const matchesType = typeFilter === 'all' || v.voucher_type === typeFilter;

    return matchesSearch && matchesStatus && matchesType;
  });

  const getStatusBadge = (status: PaymentStatus) => {
    switch (status) {
      case 'approved':
      case 'paid':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">
            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" /> Approved
          </span>
        );
      case 'rejected':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-rose-50 text-rose-700 border border-rose-200">
            Rejected
          </span>
        );
      case 'pending':
      default:
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-amber-50 text-amber-700 border border-amber-200">
            <Clock className="h-3.5 w-3.5 text-amber-600 animate-spin" style={{ animationDuration: '4s' }} /> Pending Approval
          </span>
        );
    }
  };

  const handleWhatsAppShare = (e: React.MouseEvent, voucher: Voucher) => {
    e.stopPropagation();
    const message = `Hello ${voucher.party_name},\n\nYour Tax Invoice *${voucher.voucher_number}* for *₹${voucher.total_amount.toLocaleString('en-IN')}* has been generated by Livekeeping Enterprises.\n\nGSTIN: ${voucher.party_gstin || 'N/A'}\nStatus: ${voucher.status.toUpperCase()}\n${voucher.irn_number ? `Government IRN: ${voucher.irn_number.substring(0, 16)}...\n` : ''}\nThank you for your business!`;
    const encoded = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  };

  return (
    <div className="space-y-4">
      {/* Search and Filters Bar */}
      <div className="p-4 rounded-2xl luxe-card flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between">
        {/* Search Input */}
        <div className="relative flex-1">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
          <input
            type="text"
            placeholder="Search party name, GSTIN, or invoice number..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs sm:text-sm font-medium text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition"
          />
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-2 overflow-x-auto pb-1 md:pb-0">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="min-h-[40px] px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold text-slate-700 focus:outline-none focus:border-blue-500"
          >
            <option value="all">All Statuses</option>
            <option value="pending">Pending Review</option>
            <option value="approved">Approved & Synced</option>
          </select>

          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="min-h-[40px] px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-semibold text-slate-700 focus:outline-none focus:border-blue-500"
          >
            <option value="all">All Voucher Types</option>
            <option value="sales_bill">Sales Bills</option>
            <option value="quotation">Quotations</option>
            <option value="receipt">Payment Receipts</option>
          </select>
        </div>
      </div>

      {/* ================= MOBILE VIEW: TOUCH-FRIENDLY CARD STACK (< 768px) ================= */}
      <div className="md:hidden space-y-3">
        {filteredVouchers.map((voucher) => (
          <div
            key={voucher.id}
            onClick={() => onSelectVoucher(voucher)}
            className="p-4 rounded-2xl luxe-card cursor-pointer space-y-3 relative active:scale-[0.99] transition"
          >
            <div className="flex items-start justify-between gap-2">
              <div>
                <span className="text-[11px] font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md border border-blue-100">
                  {voucher.voucher_number}
                </span>
                <h4 className="font-extrabold text-sm text-slate-900 mt-1.5 line-clamp-1">{voucher.party_name}</h4>
                <div className="text-[11px] text-slate-500 font-mono mt-0.5">GST: {voucher.party_gstin || 'Unregistered'}</div>
              </div>
              <div className="text-right">
                <div className="text-base font-extrabold text-slate-900">
                  ₹{voucher.total_amount.toLocaleString('en-IN')}
                </div>
                <div className="text-[10px] text-slate-400">Incl. ₹{voucher.tax_amount?.toLocaleString('en-IN') || 0} GST</div>
              </div>
            </div>

            <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs">
              <div>{getStatusBadge(voucher.status)}</div>

              <div className="flex items-center space-x-1.5" onClick={(e) => e.stopPropagation()}>
                <button
                  onClick={(e) => handleWhatsAppShare(e, voucher)}
                  className="min-h-[36px] px-2.5 py-1.5 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 border border-emerald-200 rounded-lg text-xs font-bold flex items-center gap-1 btn-tactile"
                >
                  <Share2 className="h-3.5 w-3.5 text-emerald-600" /> WhatsApp
                </button>

                {(activeRole === 'checker' || activeRole === 'admin') && voucher.status === 'pending' && (
                  <button
                    onClick={() => onUpdateStatus(voucher.id, 'approved')}
                    className="min-h-[36px] px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-lg text-xs shadow-md shadow-blue-600/20 btn-tactile"
                  >
                    Approve
                  </button>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* ================= DESKTOP VIEW: MULTI-COLUMN TABULAR GRID (>= 768px) ================= */}
      <div className="hidden md:block rounded-2xl luxe-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50/80 text-[11px] font-extrabold uppercase tracking-wider text-slate-600">
                <th className="py-3.5 px-4">Voucher No</th>
                <th className="py-3.5 px-4">Party / Customer</th>
                <th className="py-3.5 px-4">Type</th>
                <th className="py-3.5 px-4 text-right">Tax (GST)</th>
                <th className="py-3.5 px-4 text-right">Total Amount</th>
                <th className="py-3.5 px-4 text-center">Status</th>
                <th className="py-3.5 px-4 text-center">E-Invoice IRN</th>
                <th className="py-3.5 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-xs">
              {filteredVouchers.map((voucher) => (
                <tr
                  key={voucher.id}
                  onClick={() => onSelectVoucher(voucher)}
                  className="hover:bg-blue-50/40 cursor-pointer transition"
                >
                  <td className="py-3.5 px-4 font-mono font-bold text-blue-600 whitespace-nowrap">
                    {voucher.voucher_number}
                  </td>
                  <td className="py-3.5 px-4">
                    <div className="font-bold text-slate-900">{voucher.party_name}</div>
                    <div className="text-[11px] text-slate-400 font-mono">{voucher.party_gstin || 'Unregistered'}</div>
                  </td>
                  <td className="py-3.5 px-4 capitalize font-medium text-slate-600">
                    <span className="px-2 py-0.5 rounded-md bg-slate-100 text-slate-700 text-[11px]">
                      {voucher.voucher_type.replace('_', ' ')}
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-right font-mono text-slate-500">
                    ₹{voucher.tax_amount?.toLocaleString('en-IN') || 0}
                  </td>
                  <td className="py-3.5 px-4 text-right font-bold text-slate-900 font-mono text-sm">
                    ₹{voucher.total_amount.toLocaleString('en-IN')}
                  </td>
                  <td className="py-3.5 px-4 text-center whitespace-nowrap">
                    {getStatusBadge(voucher.status)}
                  </td>
                  <td className="py-3.5 px-4 text-center whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                    {voucher.irn_number ? (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-purple-50 text-purple-700 border border-purple-200">
                        <ShieldCheck className="h-3 w-3 text-purple-600" /> IRN Generated
                      </span>
                    ) : (
                      <button
                        onClick={() => onGenerateIrn(voucher.id)}
                        disabled={generatingIrnId === voucher.id}
                        className="px-2.5 py-1 text-[11px] font-bold text-indigo-600 bg-indigo-50 hover:bg-indigo-100 rounded-lg border border-indigo-200 transition btn-tactile disabled:opacity-50"
                      >
                        {generatingIrnId === voucher.id ? (
                          <span className="flex items-center gap-1">
                            <RefreshCw className="h-3 w-3 animate-spin" /> Generating...
                          </span>
                        ) : (
                          '1-Click IRN'
                        )}
                      </button>
                    )}
                  </td>
                  <td className="py-3.5 px-4 text-right whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                    <div className="flex items-center justify-end space-x-1.5">
                      <button
                        onClick={(e) => handleWhatsAppShare(e, voucher)}
                        title="Send Bill via WhatsApp"
                        className="p-1.5 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 border border-emerald-200 rounded-lg transition btn-tactile"
                      >
                        <Share2 className="h-4 w-4 text-emerald-600" />
                      </button>

                      {(activeRole === 'checker' || activeRole === 'admin') && voucher.status === 'pending' && (
                        <button
                          onClick={() => onUpdateStatus(voucher.id, 'approved')}
                          className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-lg text-xs shadow-sm shadow-blue-600/30 btn-tactile"
                        >
                          Approve
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
