'use client';

import React, { useState } from 'react';
import { Voucher, UserRole, PaymentStatus } from '@/types/database';
import { 
  FileText, 
  CheckCircle2, 
  Clock, 
  Send, 
  QrCode, 
  Eye, 
  Filter, 
  Search, 
  ArrowUpDown,
  Building,
  Calendar,
  IndianRupee,
  ShieldCheck,
  RefreshCw,
  Share2,
  ChevronRight,
  Edit3,
  Trash2
} from 'lucide-react';

interface VoucherListProps {
  vouchers: Voucher[];
  activeRole: UserRole;
  isLoading?: boolean;
  onSelectVoucher: (voucher: Voucher) => void;
  onUpdateStatus: (id: string, status: PaymentStatus) => void;
  onGenerateIrn: (id: string) => void;
  generatingIrnId: string | null;
  onEditVoucher?: (voucher: Voucher) => void;
  onDeleteVoucher?: (id: string) => void;
}

export default function VoucherList({
  vouchers,
  activeRole,
  isLoading = false,
  onSelectVoucher,
  onUpdateStatus,
  onGenerateIrn,
  generatingIrnId,
  onEditVoucher,
  onDeleteVoucher
}: VoucherListProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<string>('all');

  const filteredVouchers = vouchers.filter((v) => {
    const matchesSearch = 
      v.party_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      v.voucher_number.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (v.party_gstin && v.party_gstin.toLowerCase().includes(searchTerm.toLowerCase()));

    const matchesStatus = statusFilter === 'all' || v.status === statusFilter;
    const matchesType = typeFilter === 'all' || v.voucher_type === typeFilter;

    return matchesSearch && matchesStatus && matchesType;
  });

  const getStatusBadge = (status: PaymentStatus) => {
    switch (status) {
      case 'approved':
      case 'paid':
        return (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-bold bg-[#D2DEC9] text-[#2b3e24]">
            <CheckCircle2 className="h-3.5 w-3.5 text-[#2b3e24]" /> Approved
          </span>
        );
      case 'rejected':
        return (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-bold bg-[#F8D7DA] text-[#721C24]">
            Rejected
          </span>
        );
      case 'pending':
      default:
        return (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-bold bg-[#FBE29D] text-[#4d3809]">
            <Clock className="h-3.5 w-3.5 text-[#4d3809] animate-spin" style={{ animationDuration: '4s' }} /> Pending Review
          </span>
        );
    }
  };

  const handleWhatsAppShare = (e: React.MouseEvent, voucher: Voucher) => {
    e.stopPropagation();
    const message = `Hello ${voucher.party_name},\n\nYour Tax Invoice *${voucher.voucher_number}* for *₹${voucher.total_amount.toLocaleString('en-IN')}* has been generated by Livekeeping Enterprises.\n\nGSTIN: ${voucher.party_gstin || 'N/A'}\nStatus: ${voucher.status.toUpperCase()}\n${voucher.irn_number ? `Government IRN: ${voucher.irn_number.substring(0, 16)}...\n` : ''}\nThank you for your business!`;
    const encoded = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  };

  return (
    <div className="space-y-4">
      {/* Search and Filters Bar */}
      <div className="p-4 rounded-[28px] bg-[#fafaf8] border border-[#e5e3dc] flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between">
        {/* Search Input */}
        <div className="relative flex-1">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-[#88898b]" />
          <input
            type="text"
            placeholder="Search party name, GSTIN, or invoice number..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-11 pr-4 py-2.5 bg-[#f6f5f0] border-none rounded-full text-xs sm:text-sm font-medium text-[#232528] placeholder-[#88898b] focus:outline-none focus:ring-2 focus:ring-[#f5ba41]"
          />
        </div>

        {/* Filter Selects */}
        <div className="flex items-center gap-2 overflow-x-auto pb-1 md:pb-0">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="min-h-[40px] px-4 py-2 bg-[#f6f5f0] border-none rounded-full text-xs font-bold text-[#232528] focus:outline-none focus:ring-2 focus:ring-[#f5ba41]"
          >
            <option value="all">All Statuses</option>
            <option value="pending">Pending Review</option>
            <option value="approved">Approved & Synced</option>
          </select>

          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="min-h-[40px] px-4 py-2 bg-[#f6f5f0] border-none rounded-full text-xs font-bold text-[#232528] focus:outline-none focus:ring-2 focus:ring-[#f5ba41]"
          >
            <option value="all">All Types</option>
            <option value="sales_bill">Sales Bills</option>
            <option value="quotation">Quotations</option>
            <option value="receipt">Receipts</option>
          </select>
        </div>
      </div>

      {/* Loading Skeletons */}
      {isLoading ? (
        <>
          {/* Mobile Loading Skeletons */}
          <div className="flex flex-col space-y-4 md:hidden">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="p-4 rounded-[24px] bg-[#fafaf8] border border-[#e5e3dc] animate-pulse space-y-3">
                <div className="flex justify-between items-start">
                  <div className="space-y-2">
                    <div className="h-4 w-24 bg-[#e5e3dc] rounded-full"></div>
                    <div className="h-5 w-40 bg-[#e5e3dc] rounded-md"></div>
                    <div className="h-3 w-28 bg-[#e5e3dc] rounded-full"></div>
                  </div>
                  <div className="space-y-2 text-right">
                    <div className="h-6 w-20 bg-[#e5e3dc] rounded-md ml-auto"></div>
                    <div className="h-3 w-14 bg-[#e5e3dc] rounded-full ml-auto"></div>
                  </div>
                </div>
                <div className="pt-2 border-t border-[#efeee9] flex justify-between items-center">
                  <div className="h-6 w-24 bg-[#e5e3dc] rounded-full"></div>
                  <div className="h-8 w-20 bg-[#e5e3dc] rounded-full"></div>
                </div>
              </div>
            ))}
          </div>

          {/* Desktop Loading Skeletons */}
          <div className="hidden md:block rounded-[28px] bg-[#fafaf8] border border-[#e5e3dc] overflow-hidden">
            <div className="overflow-x-auto w-full">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-[#e5e3dc] bg-[#f6f5f0] text-[11px] font-extrabold uppercase tracking-wider text-[#88898b]">
                    <th className="py-4 px-6">Voucher No</th>
                    <th className="py-4 px-6">Party / Customer</th>
                    <th className="py-4 px-6">Type</th>
                    <th className="py-4 px-6 text-right">Tax (GST)</th>
                    <th className="py-4 px-6 text-right">Total Amount</th>
                    <th className="py-4 px-6 text-center">Status</th>
                    <th className="py-4 px-6 text-center">E-Invoice IRN</th>
                    <th className="py-4 px-6 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#efeee9] text-xs">
                  {[1, 2, 3, 4, 5].map((i) => (
                    <tr key={i} className="animate-pulse">
                      <td className="py-4 px-6"><div className="h-4 w-20 bg-[#e5e3dc] rounded-full"></div></td>
                      <td className="py-4 px-6 space-y-1.5"><div className="h-4 w-36 bg-[#e5e3dc] rounded"></div><div className="h-3 w-24 bg-[#e5e3dc] rounded-full"></div></td>
                      <td className="py-4 px-6"><div className="h-5 w-20 bg-[#e5e3dc] rounded-full"></div></td>
                      <td className="py-4 px-6 text-right"><div className="h-4 w-16 bg-[#e5e3dc] rounded ml-auto"></div></td>
                      <td className="py-4 px-6 text-right"><div className="h-5 w-24 bg-[#e5e3dc] rounded ml-auto"></div></td>
                      <td className="py-4 px-6 text-center"><div className="h-6 w-20 bg-[#e5e3dc] rounded-full mx-auto"></div></td>
                      <td className="py-4 px-6 text-center"><div className="h-6 w-20 bg-[#e5e3dc] rounded-full mx-auto"></div></td>
                      <td className="py-4 px-6 text-right"><div className="h-8 w-24 bg-[#e5e3dc] rounded-full ml-auto"></div></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </>
      ) : filteredVouchers.length === 0 ? (
        <div className="p-12 text-center rounded-[28px] bg-[#fafaf8] border border-[#e5e3dc]">
          <FileText className="h-10 w-10 text-[#88898b] mx-auto mb-3 opacity-40" />
          <h3 className="text-base font-bold text-[#232528]">No Vouchers Found</h3>
          <p className="text-xs text-[#88898b] mt-1 max-w-sm mx-auto">
            {searchTerm || statusFilter !== 'all' || typeFilter !== 'all'
              ? 'No records match your active search or filters. Try resetting filters.'
              : 'No accounting vouchers are recorded yet. Create a voucher to get started.'}
          </p>
        </div>
      ) : (
        <>
          {/* ================= MOBILE VIEW: TOUCH-FRIENDLY CARD STACK (< 768px) ================= */}
          <div className="flex flex-col space-y-4 md:hidden">
            {filteredVouchers.map((voucher) => (
              <div
                key={voucher.id}
                onClick={() => onSelectVoucher(voucher)}
                className="p-4 rounded-[24px] bg-[#fafaf8] border border-[#e5e3dc] cursor-pointer space-y-3 relative active:scale-[0.99] transition"
              >
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <span className="text-[11px] font-bold text-[#232528] bg-[#f6f5f0] px-2.5 py-1 rounded-full">
                      {voucher.voucher_number}
                    </span>
                    <h4 className="font-extrabold text-sm text-[#232528] mt-2 line-clamp-1">{voucher.party_name}</h4>
                    <div className="text-[11px] text-[#88898b] font-mono mt-0.5">GST: {voucher.party_gstin || 'Unregistered'}</div>
                  </div>
                  <div className="text-right">
                    <div className="text-base font-black text-[#232528] font-mono">
                      ₹{voucher.total_amount.toLocaleString('en-IN')}
                    </div>
                    <div className="text-[10px] text-[#88898b]">Tax: ₹{voucher.tax_amount?.toLocaleString('en-IN') || 0}</div>
                  </div>
                </div>

                <div className="pt-2 border-t border-[#efeee9] flex items-center justify-between text-xs">
                  <div>{getStatusBadge(voucher.status)}</div>

                  <div className="flex items-center space-x-1.5" onClick={(e) => e.stopPropagation()}>
                    {onEditVoucher && (
                      <button
                        onClick={() => onEditVoucher(voucher)}
                        title="Edit Voucher"
                        className="p-2 bg-[#f6f5f0] hover:bg-[#edece6] text-[#232528] rounded-full transition btn-pill"
                      >
                        <Edit3 className="h-3.5 w-3.5 text-[#88898b]" />
                      </button>
                    )}

                    {onDeleteVoucher && (activeRole === 'admin' || activeRole === 'manager' || activeRole === 'checker') && (
                      <button
                        onClick={() => {
                          if (window.confirm(`Delete voucher ${voucher.voucher_number}?`)) {
                            onDeleteVoucher(voucher.id);
                          }
                        }}
                        title="Delete Voucher"
                        className="p-2 bg-[#fbeaea] hover:bg-[#f7d6d6] text-[#b91c1c] rounded-full transition btn-pill"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    )}

                    <button
                      onClick={(e) => handleWhatsAppShare(e, voucher)}
                      className="min-h-[36px] px-3 py-1.5 bg-[#D2DEC9] text-[#2b3e24] font-bold rounded-full text-xs flex items-center gap-1 btn-pill"
                    >
                      <Share2 className="h-3.5 w-3.5" /> WhatsApp
                    </button>

                    {(activeRole === 'checker' || activeRole === 'admin') && voucher.status === 'pending' && (
                      <button
                        onClick={() => onUpdateStatus(voucher.id, 'approved')}
                        className="min-h-[36px] px-4 py-1.5 bg-[#f5ba41] hover:bg-[#e6ab33] text-[#232528] font-bold rounded-full text-xs btn-pill"
                      >
                        Approve
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* ================= DESKTOP VIEW: TABULAR LIST (>= 768px) ================= */}
          <div className="hidden md:block rounded-[28px] bg-[#fafaf8] border border-[#e5e3dc] overflow-hidden">
            <div className="overflow-x-auto w-full">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-[#e5e3dc] bg-[#f6f5f0] text-[11px] font-extrabold uppercase tracking-wider text-[#88898b]">
                    <th className="py-4 px-6">Voucher No</th>
                    <th className="py-4 px-6">Party / Customer</th>
                    <th className="py-4 px-6">Type</th>
                    <th className="py-4 px-6 text-right">Tax (GST)</th>
                    <th className="py-4 px-6 text-right">Total Amount</th>
                    <th className="py-4 px-6 text-center">Status</th>
                    <th className="py-4 px-6 text-center">E-Invoice IRN</th>
                    <th className="py-4 px-6 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#efeee9] text-xs">
                  {filteredVouchers.map((voucher) => (
                    <tr
                      key={voucher.id}
                  onClick={() => onSelectVoucher(voucher)}
                  className="hover:bg-[#f6f5f0]/80 cursor-pointer transition"
                >
                  <td className="py-4 px-6 font-mono font-bold text-[#232528] whitespace-nowrap">
                    {voucher.voucher_number}
                  </td>
                  <td className="py-4 px-6">
                    <div className="font-extrabold text-sm text-[#232528]">{voucher.party_name}</div>
                    <div className="text-[11px] text-[#88898b] font-mono">{voucher.party_gstin || 'Unregistered'}</div>
                  </td>
                  <td className="py-4 px-6 capitalize font-medium text-[#88898b]">
                    <span className="px-2.5 py-1 rounded-full bg-[#f6f5f0] text-[#232528] text-[11px] font-bold">
                      {voucher.voucher_type.replace('_', ' ')}
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right font-mono text-[#88898b]">
                    ₹{voucher.tax_amount?.toLocaleString('en-IN') || 0}
                  </td>
                  <td className="py-4 px-6 text-right font-black text-[#232528] font-mono text-sm">
                    ₹{voucher.total_amount.toLocaleString('en-IN')}
                  </td>
                  <td className="py-4 px-6 text-center whitespace-nowrap">
                    {getStatusBadge(voucher.status)}
                  </td>
                  <td className="py-4 px-6 text-center whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                    {voucher.irn_number ? (
                      <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-[10px] font-bold bg-[#8F94FB]/20 text-[#4c50b8]">
                        <ShieldCheck className="h-3.5 w-3.5 text-[#5b5fd8]" /> IRN Active
                      </span>
                    ) : (
                      <button
                        onClick={() => onGenerateIrn(voucher.id)}
                        disabled={generatingIrnId === voucher.id}
                        className="px-3 py-1 text-[11px] font-bold text-white bg-[#8F94FB] hover:bg-[#7d82f2] rounded-full transition btn-pill disabled:opacity-50"
                      >
                        {generatingIrnId === voucher.id ? 'Generating...' : '1-Click IRN'}
                      </button>
                    )}
                  </td>
                  <td className="py-4 px-6 text-right whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                    <div className="flex items-center justify-end space-x-1.5">
                      {onEditVoucher && (
                        <button
                          onClick={() => onEditVoucher(voucher)}
                          title="Edit Voucher"
                          className="p-2 bg-[#f6f5f0] hover:bg-[#edece6] text-[#232528] rounded-full transition btn-pill"
                        >
                          <Edit3 className="h-3.5 w-3.5 text-[#88898b]" />
                        </button>
                      )}

                      {onDeleteVoucher && (activeRole === 'admin' || activeRole === 'manager' || activeRole === 'checker') && (
                        <button
                          onClick={() => {
                            if (window.confirm(`Delete voucher ${voucher.voucher_number}?`)) {
                              onDeleteVoucher(voucher.id);
                            }
                          }}
                          title="Delete Voucher"
                          className="p-2 bg-[#fbeaea] hover:bg-[#f7d6d6] text-[#b91c1c] rounded-full transition btn-pill"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      )}

                      <button
                        onClick={(e) => handleWhatsAppShare(e, voucher)}
                        title="Send on WhatsApp"
                        className="p-2 bg-[#D2DEC9] hover:bg-[#c2d2b7] text-[#2b3e24] rounded-full transition btn-pill"
                      >
                        <Share2 className="h-3.5 w-3.5" />
                      </button>

                      {(activeRole === 'checker' || activeRole === 'admin') && voucher.status === 'pending' && (
                        <button
                          onClick={() => onUpdateStatus(voucher.id, 'approved')}
                          className="px-4 py-1.5 bg-[#f5ba41] hover:bg-[#e6ab33] text-[#232528] font-bold rounded-full text-xs btn-pill"
                        >
                          Approve
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  )}
</div>
);
}
